version: 2

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gulp
    versions:
    - "> 3.9.1"
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.17.0
    - 4.22.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: "@babel/plugin-proposal-object-rest-spread"
    versions:
    - 7.12.13
    - 7.13.0
    - 7.13.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
  - dependency-name: table
    versions:
    - 6.3.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.22.0
  - dependency-name: eslint
    versions:
    - 7.24.0
